{{ if .Values.server.config.daily_reboot.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
  namespace:  {{ .Release.Namespace }}
spec:
  concurrencyPolicy:  Forbid
  schedule: "{{ .Values.server.config.daily_reboot.time }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds:  600
      template:
        spec:
          serviceAccountName: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
          restartPolicy:  Never
          containers:
            - name: kubectl
              image:  bitnami/kubectl@sha256:e2b97dde9666986c61c56d49aae85a714b89b69392baa531438e74ec34096fb4
              command:
              - kubectl
              - -n
              - {{ .Release.Namespace }}
              - rollout
              - restart
              - deployment/{{ .Release.Name }}-server
{{ end }}