{{ if .Values.server.config.daily_reboot.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
  namespace:  {{ .Release.Namespace }}
spec:
  concurrencyPolicy:  Forbid
  schedule: "{{ .Values.server.config.daily_reboot.time }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds:  600
      template:
        spec:
          serviceAccountName: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
          restartPolicy:  Never
          containers:
            - name: kubectl
              image:  bitnami/kubectl@sha256:4cab0102df3b978f1bbf6f15b3c06f56c6e885ea7c740d81268435a266dfe442
              command:
              - kubectl
              - -n
              - {{ .Release.Namespace }}
              - rollout
              - restart
              - deployment/{{ .Release.Name }}-server
{{ end }}