{{ if .Values.server.config.daily_reboot.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
  namespace:  {{ .Release.Namespace }}
spec:
  concurrencyPolicy:  Forbid
  schedule: "{{ .Values.server.config.daily_reboot.time }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds:  600
      template:
        spec:
          serviceAccountName: "{{ .Values.server.config.daily_reboot.serviceAccount }}"
          restartPolicy:  Never
          containers:
            - name: kubectl
              image:  bitnami/kubectl@sha256:b9f4412e53f09d76b0991cdd29c0feff4c1d1e112b307e0ab155e5b050a9f4ec
              command:
              - kubectl
              - -n
              - {{ .Release.Namespace }}
              - rollout
              - restart
              - deployment/{{ .Release.Name }}-server
{{ end }}